server:
  port: 80
spring:
  application:
    name: app-meite-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

zuul:
  routes:
    api-weixin:
      serviceId: app-meite-weixin
      path: /api-weixin/**
    api-member:
      serviceId: app-meite-member
      path: /api-member/**

#读取swagger文档
swagger-resource:
  list:
    - resrouce:
      name: api-meite-weixin
      location: /app-meite-weixin/v2/api-docs
      version: 2.0
    - resrouce:
      name: api-meite-member
      location: /app-meite-member/v2/api-docs
      version: 2.0   