server:
  port: 8200
spring:
  application:
    name: app-meite-weixin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
  instance:
    prefer-ip-address: true
swagger:
  base-package: com.meite.weixin.service
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 学习SpringClound
  version: 1.0
  terms-of-service-url: www.meite.com
  contact:
    name: Kero
    email: kero@163.com
