spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/z_cloud01?useSSl=false
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
# mybatis相关配置  
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml  # mybatis全局配置文件
  type-aliases-package: com.kero.springcloud.entities # 使用别名的包所在的位置
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml  # mbatis的Mapper接口所在的包的位置

# eureka相关配置    
eureka:
  client:
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microsevicecloud-dept8001  #自定义服务名称
    prefer-ip-address: true   #访问路径可以显示IP地址  
    
# info相关配置 
info:     
  app.name: kero-microservicecloud  #定制服务的名称
  company.name: www.kero.com  #定制公司的名称
  build.artifactId: $project.artifactId$  #显示工程的版本id
  build.version: $project.version$   #显示工程的版本号     
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/z_cloud02?useSSl=false
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
# mybatis相关配置  
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml  # mybatis全局配置文件
  type-aliases-package: com.kero.springcloud.entities # 使用别名的包所在的位置
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml  # mbatis的Mapper接口所在的包的位置

# eureka相关配置    
eureka:
  client:
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microsevicecloud-dept8001  #自定义服务名称
    prefer-ip-address: true   #访问路径可以显示IP地址  
    
# info相关配置 
info:     
  app.name: kero-microservicecloud  #定制服务的名称
  company.name: www.kero.com  #定制公司的名称
  build.artifactId: $project.artifactId$  #显示工程的版本id
  build.version: $project.version$   #显示工程的版本号     
